version: '3.8'
services:
  # Database
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=bonvoyage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=skopje
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  # Backend
  # Frontend