### login sucess
POST http://localhost:8080/login
Content-Type: application/json

{"username":"lostparadise","password":"sd123"}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  var jwt=response.body
  client.global.set("jwt", response.body)
});
%}

###

GET http://localhost:8080/vehicles
Authorization: Bearer {{jwt}}

###
